### ISSUE TITLE
Add acceptance callback

### ISSUE THREAD

**Issue by fnando** [codermarcos/simple-mask-money#12]
Right now there's no way of rejecting a value change (let's say I want to cap the amount from 10.00 to 9999.99).

Having two options like `min` and `max` or even making it more flexible with `acceptAmount=callback`, which should return `true` or `false` to accept or reject the change.

**Comment by codermarcos** [comment]
Again thank you for your issue @fnando . 😄 👍 
Very good feature, again feel free to open a pull request or do some kind of refactor but in any case this will be included in the next versions.

**Comment by codermarcos** [comment]
This feature was included in the [v3.0.0](https://github.com/codermarcos/simple-mask-money/releases/tag/v3.0.0)

**Comment by DowsingUK** [comment]
Where can I find documentation for this feature?, thanks
