### ISSUE TITLE
SimpleMaskMoney format should accept options

### ISSUE THREAD

**Issue by fnando** [codermarcos/simple-mask-money#13]
Given that `SimpleMaskMoney.format` is an static method, it should also accept the formatting options as a second argument, defaulting to whatever it's set on `SimpleMaskMoney.args`.

**Comment by codermarcos** [comment]
Many thanks for your issue. 😄 👍 
It makes sense, but it's also cool to have global formatting. Feel free to open a pull request including this or do some refactoring, but in any case this will be included in the next versions.

**Comment by codermarcos** [comment]
This feature was included in the [v3.0.0](https://github.com/codermarcos/simple-mask-money/releases/tag/v3.0.0)
