### ISSUE TITLE
SimpleMaskMoney.format(0.1) returns `0.01`

### ISSUE THREAD

**Issue by fnando** [codermarcos/simple-mask-money#14]
Apparently any number smaller than 1 with 1 decimal place is returning a number divided by 10.

```js
SimpleMaskMoney.format(0.1)
//=> "0,01"
SimpleMaskMoney.format(0.11)
//=> "0,11"
SimpleMaskMoney.format(0.9)
//=>  "0,09"
```

**Comment by codermarcos** [comment]
Bug fixed in version [v2.0.0](https://github.com/codermarcos/simple-mask-money/releases/tag/v2.0.0)

**Comment by codermarcos** [comment]
This feature was included in the [v3.0.0](https://github.com/codermarcos/simple-mask-money/releases/tag/v3.0.0)

**Comment by joaofeliperm** [comment]
@codermarcos , when the latest version will be available on npm?

**Comment by codermarcos** [comment]
@joaofeliperm sorry, i'm late. The version 3 will have many break changes, i believe that docs need to improve a bit more.
