### ISSUE TITLE
fractionDigits in 0

### ISSUE THREAD

**Issue by vahidalvandi** [codermarcos/simple-mask-money#16]
i need set fractionDigits to 0
i need like this 1,000 
but if set to 0 not work any thing

**Comment by codermarcos** [comment]
Many thanks for your issue. 😄 👍
This bug really exists, when you define 0 to fractionDigits, the thousands separators does not work. 
Feel free to open a pull request including this or do some refactoring, but in any case this will be included in the next versions.

**Comment by vahidalvandi** [comment]
thank you . you plugin is cool !
