### ISSUE TITLE
No work with different arguments for various fields

### ISSUE THREAD

**Issue by kaacyn** [codermarcos/simple-mask-money#19]
Exemple for first field: 
fractionDigits: 2

For second field in same page: 
fractionDigits: 5

In this exemple, the first field inherits the formatting of the second.

great library, thank you

**Comment by codermarcos** [comment]
First thank you very much for opening an issue, it helps improve the quality of our package. 😄 👍
What version are you using? And can you add the configuration you are using? To help reproduce the error!
Put an end if you identify the source of the error feel free to open a pull request including its fix or do some refactoring, but anyway as soon as you identify the problem this will be solved and ready for future releases.

**Comment by kaacyn** [comment]
I created an example in https://jsfiddle.net/kaacyn/mkc7ut49/3/

Field 1: Field 1 does not work Correctly because it conflicts with second field.

Field 2: all right.

Am I doing something wrong?
Sorry, my English is bad.

**Comment by codermarcos** [comment]
No, you're correct. This bug really exists, and will be solved along with the feature #13.
Thank you again for your help. ❤️
