### ISSUE TITLE
AutoSet carret position to last position

### ISSUE THREAD

**Issue by EduFrazao** [codermarcos/simple-mask-money#40]
Hi. How can I configure to auto-configure carret position to the last digit, when focusing field or after cleaning all values, instead of place carret right before the decimal separator?

**Comment by codermarcos** [comment]
Many thanks for your issue, we need more devs like you. :smile: :+1:
Today we have property **cursor** you can look doc [here](https://github.com/codermarcos/simple-mask-money/blame/master/docs/3.x.x/README.md#L38) but 
as I said in another issue we have the idea to change many things here this is a very simple project and has code that needs to be updated Tks :heart:

**Comment by EduFrazao** [comment]
Hi @codermarcos . Thank you very mutch to pointme to the Docs. The  cursor property works very well! I will close this issue/question!
