### ISSUE TITLE
Type `cursor: 'move'` input handler starts with cents and then moves to whole.

### ISSUE THREAD

**Issue by armoucar** [codermarcos/simple-mask-money#49]
After changing focus with keyboard (tab) in a `SimpleMaskMoney` field, we get the following behaviors:

Typing: `1111`

When `cursor: 'move'`:

![cursor-move](https://user-images.githubusercontent.com/1134016/117573140-bd328400-b0ac-11eb-97f4-ff28f99e94b5.gif)

When `cursor: 'end'`:

![cursor-end](https://user-images.githubusercontent.com/1134016/117573143-c02d7480-b0ac-11eb-9f9e-9e4ff0f7017c.gif)

**Comment by armoucar** [comment]
hi @codermarcos, would you mind accepting this one and bumping a new patch of simple-mask-money? It's a very simple fix for a very annoying bug. Thanks!

**Comment by hmilena** [comment]
@armoucar did you manage to fix this issue?

**Comment by armoucar** [comment]
I don't know what's the state of this since I'm not working on a project that has this lib as a dependency anymore. But as far as I can tell, my PR was merged, so that was supposed to be fixed.
