### ISSUE TITLE
Cursor jumps to the end

### ISSUE THREAD

**Issue by m-spyratos** [codermarcos/simple-mask-money#5]
If you place the cursor to a specific position other than the very start or end of the amount (and few other places), after entering an amount the cursor jumps to the very end instead of staying at the same position.

Here are few examples (the pipe represents the cursor):

`0.0|0` -> Enter `1`
Actual:  `0.10|`
Expected: `0.1|0`

`12.|34` -> Enter `5`
Actual: `125.34|`
Expected: `125|.34`

`1|23.45` -> Enter `6`
Actual: `1,623.45|`
Expected: `1,6|23.45`

**Comment by codermarcos** [comment]
@m-spyratos thanks for reporting this bug. In the next version this bug will be corrected with some improvements for performance and compatibilities as well.
