### ISSUE TITLE
Do not set value as 0 by default

### ISSUE THREAD

**Issue by sobrinho** [codermarcos/simple-mask-money#51]
My fields have `value=""` but when the mask is applied it defaults to `0,0` but empty have a meaning in my context.

**Comment by sobrinho** [comment]
Looks like using `fixed: false` removes the zero but then I have `_,__` which I would like to keep as empty entirely.

This line seems to be the culprit: https://github.com/codermarcos/simple-mask-money/blob/25664716e1a968d5090a928fc3f9fab8f016e5fe/src/core.js#L61

**Comment by codermarcos** [comment]
I supose that we've solved it at version 4.x.x. 
Could you try the new version? Thanks  💖
