### ISSUE TITLE
Perform cleanup

### ISSUE THREAD

**Issue by niksy** [codermarcos/simple-mask-money#53]
Is it possible to remove plugin completely with some destroy method? I don’t see anything in docs.

Basically, listener added with `addEventListener` should be removed, and anything attached to input element node should be deleted.

I can send PR if you’re interested.

**Comment by niksy** [comment]
@codermarcos is it OK to work on this?

**Comment by codermarcos** [comment]
> @codermarcos is it OK to work on this?
Of course, the package is ours from the community, all help is very welcome. ❤️

**Comment by codermarcos** [comment]
Many thanks for your issue. 😄 👍
Feel free to send your a pull request... Thanks ❤️

**Comment by codermarcos** [comment]
@niksy I supose that we've solved it at version 4.x.x. 
Could you try the new version? Thanks 💖
