### ISSUE TITLE
Disabling the mask

### ISSUE THREAD

**Issue by o-alquimista** [codermarcos/simple-mask-money#55]
I'm looking for a way to undo what `setMask()` does. I don't want the unmasked value, I just want to programatically turn it off, effectively removing the event listeners from the target `<input>` element and restoring its unmasked value.

**Comment by codermarcos** [comment]
@o-alquimista this is duplicated of #54.
Many thanks for your issue. 😄 👍
Feel free to send your a pull request... Thanks ❤️

**Comment by codermarcos** [comment]
@o-alquimista I supose that we've solved it at version 4.x.x. 
Could you try the new version? Thanks 💖
