### ISSUE TITLE
How should type definition files be used?

### ISSUE THREAD

**Issue by sakamossan** [codermarcos/simple-mask-money#56]
I tried to use the type definition files because there is a `types` directory, but the `types` directory and its contents are not included in the npm package (fetched by `npm install`). Additionally, the type definition files are also not included in the GitHub releases. It doesn't seem to be specified in the `.npmignore` file, but how are the type definition files intended to be used and committed?

when I directly run tsc on `types/simple-mask-money.d.ts`, there are some compilation errors. It seems that some modifications are necessary to use it with the latest version of TypeScript.

```
$ tsc --version
Version 5.1.6
$ tsc ./types/simple-mask-money.d.ts | grep -oP error.+ | sort | uniq -c
   5 error TS1070: 'public' modifier cannot appear on a type member.
   6 error TS1246: An interface property cannot have an initializer.
```

## ref

- https://github.com/codermarcos/simple-mask-money/issues/54
- https://github.com/codermarcos/simple-mask-money/commit/36bf1c2a536fdda8ccd6e006de6eed35834a971a

**Comment by codermarcos** [comment]
@sakamossan Sorry about that 💔! You are right it is a problem!
I will work in a new version probably next week! My plan is re-write all the package improve the code and the performance as well.
But If you really need to adjust the typing, please feel free to contribute, it will help a lot ❤️

**Comment by sakamossan** [comment]
Thank you for your response. I've created a pull request.

- https://github.com/codermarcos/simple-mask-money/pull/57
