### ISSUE TITLE
formatToNumber when number is negative

### ISSUE THREAD

**Issue by crauadams** [codermarcos/simple-mask-money#6]
SimpleMaskMoney.formatToNumber(-18748.20555) return 18748205.55 instead - 18748205.55

i do not have access to commit on branches... i suggest change the return value for method "formatToNumber" like this

`(input < 0) ? (parseFloat(retorno) * -1) : parseFloat(retorno);`

**Comment by codermarcos** [comment]
@crauadams thanks you very much for the issue. I have not started working on this feature yet but she is in the plans. If you want access just create a **PR** [Pull request](https://github.com/codermarcos/simple-mask-money/compare). 
I really would be happy 😆 for the help.

**Comment by codermarcos** [comment]
This feature was included in the [v1.3.0](https://github.com/codermarcos/simple-mask-money/releases/tag/v1.3.0)
