### ISSUE TITLE
Version 4.x.x doesn't work with vanilla javascript

### ISSUE THREAD

**Issue by stephannv** [codermarcos/simple-mask-money#61]
After upgrading to latest version `4.0.5`, my app doesn't compile due to an issue with simple mask money. I'm using esbuild:

```js
import SimpleMaskMoney from 'simple-mask-money'
```

Error:
```
 ✘ [ERROR] Could not resolve "simple-mask-money"

     app/javascript/controllers/money_input_mask_controller.js:3:28:
       3 │ import SimpleMaskMoney from 'simple-mask-money'
         ╵                             ~~~~~~~~~~~~~~~~~~~

   The path "." is not currently exported by package "simple-mask-money":

     node_modules/simple-mask-money/package.json:19:13:
       19 │   "exports": {
          ╵              ^

   None of the conditions in the package definition ("/", "/set-mask", "/remove-mask", "/format-to-number", "/create-instance-of", "/format-to-currency") match any of the currently active conditions ("browser", "default", "import", "module"):

     node_modules/simple-mask-money/package.json:19:13:
       19 │   "exports": {
          ╵              ^

   Consider enabling the "/" condition if this package expects it to be enabled. You can use "--conditions=/" to do that:

     node_modules/simple-mask-money/package.json:20:4:
       20 │     "/": {
          ╵     ~~~

   You can mark the path "simple-mask-money" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.

```

**Comment by codermarcos** [comment]
I apologize for this 😥! I'll be happy to help you😁; I just need a bit more details like...

- Are you using a bundler? Which bundler are you using?
    - If you are using, what is your configuration?
- What is your Node version?  

Would be very nice if you could create a simple example repository, [codesandbox](https://codesandbox.io/) or [replit](https://replit.com/) with this error!

**Comment by stephannv** [comment]
@codermarcos you don't need to apologize, you are doing a great job with simple mask money. Sorry for lacking info on issue, I will create a MRP for this issue.

**Comment by stephannv** [comment]
@codermarcos To reproduce this issue:

1. Create a folder. eg `mkdir issue61`

2. Create `package.json`:
```json
{
  "dependencies": {
    "simple-mask-money": "^4.0.5"
  },
  "scripts": {
    "build": "esbuild app.js --bundle"
  },

  "devDependencies": {
    "esbuild": "0.19.5"
  }
}
```

3. Run `npm install`

4. Create `app.js`:
```javascript
import SimpleMaskMoney from "simple-mask-money"
```

5. Run: `npm run build`

Or you can download the zip, extract it, run `npm install` and then `npm run build`: 
[issue61.zip](https://github.com/codermarcos/simple-mask-money/files/13034503/issue61.zip)

**Comment by codermarcos** [comment]
> @codermarcos To reproduce this issue:
> 
> 1. Create a folder. eg `mkdir issue61`
> 2. Create `package.json`:
> 
> ```json
> {
>   "dependencies": {
>     "simple-mask-money": "^4.0.5"
>   },
>   "scripts": {
>     "build": "esbuild app.js --bundle"
>   },
> 
>   "devDependencies": {
>     "esbuild": "0.19.5"
>   }
> }
> ```
> 
> 3. Run `npm install`
> 4. Create `app.js`:
> 
> ```js
> import SimpleMaskMoney from "simple-mask-money"
> ```
> 
> 5. Run: `npm run build`
> 
> Or you can download the zip, extract it, run `npm install` and then `npm run build`: [issue61.zip](https://github.com/codermarcos/simple-mask-money/files/13034503/issue61.zip)

Thank you  very much for your example this PR #64 should fix your problem!

**Comment by codermarcos** [comment]
Could you please try again in this version [v4.0.1](https://www.npmjs.com/package/simple-mask-money/v/4.0.6)?

**Comment by stephannv** [comment]
@codermarcos using v4.0.1 the problem doesn't happen.

**Comment by stephannv** [comment]
Using with v4.0.6 the problem doesn't happen. Thanks for the fix.

**Comment by codermarcos** [comment]
@stephannv Perfect, thank very much for your contribution! 💖
