### ISSUE TITLE
💡 [REQUEST] - Diretiva Vue.js 3.x

### ISSUE THREAD

**Issue by vitorccs** [codermarcos/simple-mask-money#78]
### Summary

Estou abrindo essa Issue para documentar como aplicar essa biblioteca em Vue.js 3 por meio de uma diretiva.

A vantagem dessa implementação é a facilidade e limpeza de código pois bastará usar conforme demonstro abaixo:

```vue.js
<input v-currency-mask>
```

Ou seja, dispensando a necessidade de fazer a definição de eventos para cada campo conforme exemplo que consta na documentação:
https://github.com/codermarcos/simple-mask-money/tree/main/examples/4.x.x/vue

Poderemos avaliar a possibilidade de futuramente tornar essa diretiva já disponível na biblioteca, mas documentando aqui pode ser útil para todos que tem maior urgência em usar no Vue.js

### Passo 1 - Criar a diretiva 

```vue.js
// Pode ser criada em /directives/CurrencyMask.ts

import { ObjectDirective } from 'vue'
import { setMask, removeMask } from 'simple-mask-money'

export interface ExtendedObjectDirective extends ObjectDirective {
  applied: boolean

  setMask(el: HTMLInputElement): void

  unsetMask(el: HTMLInputElement): void
}

export const CurrencyMask: ExtendedObjectDirective = {
  applied: false,

  created: (el: HTMLInputElement): void => {
    CurrencyMask.setMask(el)
  },

  mounted: (el: HTMLInputElement): void => {
    CurrencyMask.setMask(el)
  },

  updated: (el: HTMLInputElement): void => {
    CurrencyMask.setMask(el)
  },

  unmounted: (el: HTMLInputElement): void => {
    CurrencyMask.unsetMask(el)
  },

  setMask: (el: HTMLInputElement): void => {
    if (CurrencyMask.applied || !el.value) return

    setMask(el)
    CurrencyMask.applied = true
  },

  unsetMask: (el: HTMLInputElement): void => {
    removeMask(el)
    CurrencyMask.applied = false
  },
}
```

### Passo 2 - Aplicar a diretiva em main.ts ou main.js
```vue.js
import { CurrencyMask } from './directives/CurrencyMask.ts'

createApp(App)
  .directive('currency-mask', CurrencyMask)
```

Obs: nesta diretiva, observe que eu coloquei um comportamento para evitar o comportamento padrão dessa biblioteca onde ela troca o valor vazio do campo input por um valor padrão inicial (R$ 0,00) - com a diretiva acima, o elemento seguirá vazio ("") até o que o usuário comece a digitar o primeiro número - foi um ponto de usabilidade importante para a minha necessidade/aplicação, pois confundia o usuário o campo já começar com 0,00 sem ele ter digitado algo.

### Drawbacks

Impacto é tornar a biblioteca mais fácil de ser usada no Vue.js 3.x, dispensando a necessidade de criar componentes e se preocupar com o ciclo de eventos (mounted, unmounted, etc)

**Comment by codermarcos** [comment]
Primeiramente muito obrigado por sua contribuição ❤️ Toda contribuição é sempre bem vinda!
Sobre o tópico realmente a melhor implementação dela no vue seria atravez de uma diretiva! 👍
🤔 Só acho que vale a pena criar um outro package por questões de boas práticas! E o package instalar o `simple-mask-money` nele como uma depêndencia!
Ficarei super feliz 😁 em contribuir e fazer a referencia dele aqui atulizando as docs tambem recomendando o package! Oque você acha?

**Comment by vitorccs** [comment]
@codermarcos opa show, obrigado pela sugestão, de acordo! vou tentar criar nos próximos meses e lhe aviso. Vou fechar essa issue.
